//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.15 at 05:19:54 PM GMT-10:00 
//


package org.hackystat.telemetry.service.prefetch.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ChartName"/>
 *         &lt;element ref="{}ChartParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ProjectName"/>
 *         &lt;element ref="{}ProjectOwner"/>
 *         &lt;element ref="{}StartTime"/>
 *         &lt;element ref="{}AuthorizedUserName"/>
 *         &lt;element ref="{}AuthorizedUserPassword"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chartName",
    "chartParameter",
    "projectName",
    "projectOwner",
    "startTime",
    "authorizedUserName",
    "authorizedUserPassword"
})
@XmlRootElement(name = "Chart")
public class Chart {

    @XmlElement(name = "ChartName", required = true)
    protected String chartName;
    @XmlElement(name = "ChartParameter")
    protected List<ChartParameter> chartParameter;
    @XmlElement(name = "ProjectName", required = true)
    protected String projectName;
    @XmlElement(name = "ProjectOwner", required = true)
    protected String projectOwner;
    @XmlElement(name = "StartTime", required = true)
    protected String startTime;
    @XmlElement(name = "AuthorizedUserName", required = true)
    protected String authorizedUserName;
    @XmlElement(name = "AuthorizedUserPassword", required = true)
    protected String authorizedUserPassword;

    /**
     * Gets the value of the chartName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartName() {
        return chartName;
    }

    /**
     * Sets the value of the chartName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartName(String value) {
        this.chartName = value;
    }

    /**
     * Gets the value of the chartParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chartParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChartParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChartParameter }
     * 
     * 
     */
    public List<ChartParameter> getChartParameter() {
        if (chartParameter == null) {
            chartParameter = new ArrayList<ChartParameter>();
        }
        return this.chartParameter;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the projectOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectOwner() {
        return projectOwner;
    }

    /**
     * Sets the value of the projectOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectOwner(String value) {
        this.projectOwner = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the authorizedUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedUserName() {
        return authorizedUserName;
    }

    /**
     * Sets the value of the authorizedUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedUserName(String value) {
        this.authorizedUserName = value;
    }

    /**
     * Gets the value of the authorizedUserPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedUserPassword() {
        return authorizedUserPassword;
    }

    /**
     * Sets the value of the authorizedUserPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedUserPassword(String value) {
        this.authorizedUserPassword = value;
    }

}
