//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.18 at 06:51:58 AM HST 
//


package org.hackystat.telemetry.service.prefetch.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ChartName"/>
 *         &lt;element ref="{}ChartParameters" minOccurs="0"/>
 *         &lt;element ref="{}ProjectName"/>
 *         &lt;element ref="{}ProjectOwner"/>
 *         &lt;element ref="{}StartTime"/>
 *         &lt;element ref="{}AuthorizedUserName"/>
 *         &lt;element ref="{}AuthorizedUserPassword"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "chartName",
    "chartParameters",
    "projectName",
    "projectOwner",
    "startTime",
    "authorizedUserName",
    "authorizedUserPassword"
})
@XmlRootElement(name = "PrefetchChart")
public class PrefetchChart {

    @XmlElement(name = "ChartName", required = true)
    protected String chartName;
    @XmlElement(name = "ChartParameters")
    protected String chartParameters;
    @XmlElement(name = "ProjectName", required = true)
    protected String projectName;
    @XmlElement(name = "ProjectOwner", required = true)
    protected String projectOwner;
    @XmlElement(name = "StartTime", required = true)
    protected String startTime;
    @XmlElement(name = "AuthorizedUserName", required = true)
    protected String authorizedUserName;
    @XmlElement(name = "AuthorizedUserPassword", required = true)
    protected String authorizedUserPassword;

    /**
     * Gets the value of the chartName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartName() {
        return chartName;
    }

    /**
     * Sets the value of the chartName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartName(String value) {
        this.chartName = value;
    }

    /**
     * Gets the value of the chartParameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartParameters() {
        return chartParameters;
    }

    /**
     * Sets the value of the chartParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartParameters(String value) {
        this.chartParameters = value;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the projectOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectOwner() {
        return projectOwner;
    }

    /**
     * Sets the value of the projectOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectOwner(String value) {
        this.projectOwner = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the authorizedUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedUserName() {
        return authorizedUserName;
    }

    /**
     * Sets the value of the authorizedUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedUserName(String value) {
        this.authorizedUserName = value;
    }

    /**
     * Gets the value of the authorizedUserPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedUserPassword() {
        return authorizedUserPassword;
    }

    /**
     * Sets the value of the authorizedUserPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedUserPassword(String value) {
        this.authorizedUserPassword = value;
    }

}
