//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.15 at 05:19:54 PM GMT-10:00 
//


package org.hackystat.telemetry.service.prefetch.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MinutesAfterMidnight"/>
 *         &lt;element ref="{}TelemetryHost"/>
 *         &lt;element ref="{}Chart" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "minutesAfterMidnight",
    "telemetryHost",
    "chart"
})
@XmlRootElement(name = "TelemetryPrefetch")
public class TelemetryPrefetch {

    @XmlElement(name = "MinutesAfterMidnight")
    protected int minutesAfterMidnight;
    @XmlElement(name = "TelemetryHost", required = true)
    protected String telemetryHost;
    @XmlElement(name = "Chart")
    protected List<Chart> chart;

    /**
     * Gets the value of the minutesAfterMidnight property.
     * 
     */
    public int getMinutesAfterMidnight() {
        return minutesAfterMidnight;
    }

    /**
     * Sets the value of the minutesAfterMidnight property.
     * 
     */
    public void setMinutesAfterMidnight(int value) {
        this.minutesAfterMidnight = value;
    }

    /**
     * Gets the value of the telemetryHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelemetryHost() {
        return telemetryHost;
    }

    /**
     * Sets the value of the telemetryHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelemetryHost(String value) {
        this.telemetryHost = value;
    }

    /**
     * Gets the value of the chart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Chart }
     * 
     * 
     */
    public List<Chart> getChart() {
        if (chart == null) {
            chart = new ArrayList<Chart>();
        }
        return this.chart;
    }

}
