/* Generated By:JavaCC: Do not edit this line. TelemetryLanguageParserImplConstants.java */
package org.hackystat.telemetry.analyzer.language.parser.impl;

public interface TelemetryLanguageParserImplConstants {

  int EOF = 0;
  int STREAMS = 5;
  int CHART = 6;
  int REPORT = 7;
  int DRAW = 8;
  int YAXIS = 9;
  int ADD = 10;
  int SUB = 11;
  int MUL = 12;
  int DIV = 13;
  int LPARA = 14;
  int RPARA = 15;
  int DOUBLEQUOTE = 16;
  int COMMA = 17;
  int SEMICOLON = 18;
  int NON_NEG_INTEGER = 19;
  int NON_NEG_DOUBLE = 20;
  int IDENTIFIER = 21;
  int LETTER = 22;
  int DIGIT = 23;
  int STRING_INTERNAL = 24;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"streams\"",
    "\"chart\"",
    "\"report\"",
    "\"draw\"",
    "\"y-axis\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\",\"",
    "\";\"",
    "<NON_NEG_INTEGER>",
    "<NON_NEG_DOUBLE>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING_INTERNAL>",
    "\"=\"",
    "\"{\"",
    "\"}\"",
  };

}
