//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.15 at 10:02:34 AM GMT-10:00 
//


package org.hackystat.telemetry.service.resource.chart.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TelemetryChartRef" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "telemetryChartRef"
})
@XmlRootElement(name = "TelemetryChartIndex")
public class TelemetryChartIndex
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "TelemetryChartRef")
    protected List<TelemetryChartRef> telemetryChartRef;

    /**
     * Gets the value of the telemetryChartRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telemetryChartRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelemetryChartRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TelemetryChartRef }
     * 
     * 
     */
    public List<TelemetryChartRef> getTelemetryChartRef() {
        if (telemetryChartRef == null) {
            telemetryChartRef = new ArrayList<TelemetryChartRef>();
        }
        return this.telemetryChartRef;
    }

    public boolean isSetTelemetryChartRef() {
        return ((this.telemetryChartRef!= null)&&(!this.telemetryChartRef.isEmpty()));
    }

    public void unsetTelemetryChartRef() {
        this.telemetryChartRef = null;
    }

}
